export const messageConstant = {
  BOARDING_HOUSE_NOT_FOUND: 'Boarding house not found',
  PHOTOS_REQUIRED: 'At least one photo is required',
  BOARDING_HOUSE_ROOM_NOT_FOUND: 'Boarding house room not found',
  IMAGE_ROOM_REQUIRED: 'At least one iamge room is required',
  BOARDING_HOUSE_FACILITY_REQUIRED: 'Boarding house facility is required',
  IMAGE_FACILITY_REQUIRED: 'At least one image facility is required',
  BOARDING_HOUSE_RULE_NOT_FOUND: 'Boarding house rule not found',
  BOARDING_HOUSE_TESTIMONY_NOT_FOUND: 'Boarding house testimony not found',
  BOARDING_HOUSE_FACILITY_NOT_FOUND: 'Boarding house facility not found',
  CITY_NOT_FOUND: 'City not found',
  TYPE_NOT_FOUND: 'Type not found',
  RULE_NOT_FOUND: 'Rule not found',
  FACILITY_NOT_FOUND: 'Facility not found',
  TESTIMONY_NOT_FOUND: 'Testimony not found',
};
